BATCH_SIZE = 'batch_size'
BATCH_SIZE_TEST = 'batch_size_test'
EPOCHS = 'epochs'
LEARNING_RATE = 'learning_rate'
DEBUG = 'debug'
SAVE_MODEL = 'save_model'
ALLOW_EARLY_STOP = 'allow_early_stop'
EARLY_STOP_ALLOWED_DETERIORATION = 'early_stop_allowed_deterioration'
